---
title: A. Spies
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  publications:
    title: Publications
    output: true
    permalink: "/:collection/:path/"
  talks:
    title: Talks
    output: true
    permalink: "/:collection/:path/"
  teaching:
    title: Teaching
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: ''
    type: teaching
  values:
    layout: single
    author_profile: true
    share: true
    comments: false
    sidebar: false
- scope:
    path: ''
    type: publications
  values:
    layout: single
    author_profile: true
    share: true
    comments: true
- scope:
    path: ''
    type: talks
  values:
    layout: talk
    author_profile: false
    share: true
locale: en-GB
title_separator: "-"
name: Alexander Fabian Spies
description: Ph.D. Candidate at Imperial College London
url: https://afspies.com
baseurl: ''
repository: afspies/academic-page
teaser: 
breadcrumbs: false
words_per_minute: 160
future: true
read_more: disabled
talkmap_link: false
comments:
  provider: commentbox
  commentbox:
    project_id: 5735519099027456-proj
staticman:
  allowedFields:
    - name
    - email
    - url
    - message
  branch: gh-pages
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: _data/comments/{options.slug}
  requiredFields:
  - name
  - email
  - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  path: 
google_site_verification: 
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
twitter:
  username: 
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: google-universal
  google:
    tracking_id: UA-121968075-1
author:
  name: Alex Spies
  avatar: profile.jpg
  bio: Research Fellow @ <a href='https://www.nii.ac.jp/en/'>NII</a><br/> PhD Candidate @ <a href='https://www.imperial.ac.uk/computing'>ICL</a><br/>
    Mechanistic Interpretability & Object-Centric Representations
  location: 
  employer: Imperial College London
  googlescholar: https://scholar.google.com/citations?user=Jfp2pAQAAAAJ
  email: alex@afspies.com
  uri: 
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: 
  foursquare: 
  github: afspies
  google_plus: 
  keybase: 
  instagram: 
  impactstory: 
  lastfm: 
  linkedin: afspies
  orcid: https://orcid.org/0000-0002-8708-1530
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: afspies
  vine: 
  weibo: 
  xing: 
  youtube: 
  wikipedia: 
include:
- ".htaccess"
- _pages
- files
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Capfile
- Gemfile
- Gruntfile.js
- LICENSE
- README
- Rakefile
- assets/js/_main.js
- assets/js/plugins
- assets/js/vendor
- config
- gulpfile.js
- log
- node_modules
- package.json
- tmp
- vendor
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-redirect-from
- jekyll-toc
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
